Repository wyncode/c39_bike_shop, pull requests merged in 2020-11, with the labels that each got.

#9 Controllers models team
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/components/ContextDemo.jsx
  client/src/components/styles/.keep
  client/src/pages/Home.js
  server/app.js
  server/controllers/bikeshop.js
  server/controllers/cyclist.js
  server/controllers/repair.js
  server/controllers/reviews.js
  server/db/config/index.js
  server/db/models/bikeshop.js
  server/db/models/cyclist.js
  server/db/models/repair.js
  server/db/models/reviews.js
  server/db/models/serviceOrder.js
  server/middleware/authentication/index.js
  server/notifications/emails/index.js
  server/notifications/texts/index.js
  server/routes/open/index.js
  server/routes/secure/.keep
  server/routes/secure/bikeshop.js
  server/routes/secure/cyclist.js
  server/routes/secure/repair.js
  server/routes/secure/reviews.js
  yarn.lock
Labels: enhancement

#15 Shop list page Danny
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/App.jsx
  client/src/components/BikeShopCard.js
  client/src/components/RepairCarousel.js
  client/src/components/SearchBar.js
  client/src/components/SearchResults.js
  client/src/context/AppContext.js
  client/src/index.js
  client/src/pages/Home.js
  client/src/pages/Login.js
  client/src/pages/Shoplist.js
  client/src/pages/Signup.js
  client/yarn.lock
  server/db/models/.keep
  server/routes/open/index.js
  server/temp/mongoose.js
  yarn.lock
Labels: enhancement

#17 Repair popup components
  client/src/App.js
  client/src/components/FilterRepair.js
  client/src/components/RepairPopUp.js
  client/src/components/RepairSelection.js
  client/src/pages/Repairs.js
Labels: enhancement

#20 Bike shop pdp danny
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/BikeShopCard.js
  client/src/components/Calendar.js
  client/src/components/Map.js
  client/src/components/RepairCarousel.js
  client/src/components/ShopInfo.js
  client/src/pages/Apointment.js
  client/src/pages/BikeShopPDP.js
  client/src/pages/Repairs.js
  client/src/pages/Shoplist.js
  client/yarn.lock
Labels: enhancement

#14 Testing-Basic-Routes
  client/src/components/styles/.keep
  package.json
  server/app.js
  server/controllers/bikeshop.js
  server/controllers/cyclist.js
  server/controllers/repair.js
  server/controllers/reviews.js
  server/controllers/user.js
  server/db/models/bikeshop.js
  server/db/models/cyclist.js
  server/db/models/repair.js
  server/db/models/reviews.js
  server/db/models/serviceOrder.js
  server/db/models/user.js
  server/emails/.keep
  server/middleware/authentication/.keep
  server/middleware/authentication/index.js
  server/middleware/authorization/.keep
  server/middleware/authorization/index.js
  server/routes/open/index.js
  server/routes/secure/bikeshop.js
  server/routes/secure/cyclist.js
  server/routes/secure/repair.js
  server/routes/secure/reviews.js
  server/routes/secure/user.js
  yarn.lock
Labels: enhancement

#25 Service order routes and controllers
  server/app.js
  server/controllers/bikeshop.js
  server/controllers/cyclist.js
  server/controllers/reviews.js
  server/controllers/serviceOrder.js
  server/db/models/bicycle.js
  server/db/models/bikeshop.js
  server/db/models/cyclist.js
  server/db/models/serviceOrder.js
  server/routes/secure/.keep
  server/routes/secure/reviews.js
  server/routes/secure/serviceorder.js
Labels: enhancement

#39 Creating summary page danny
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/components/HeroImage.js
  client/src/components/styles/appointment.css
  client/src/components/styles/summary.css
  client/src/pages/Appointment.js
  client/src/pages/Confirmation.js
  client/src/pages/Summary.js
  client/yarn.lock
  server/controllers/bikeshop.js
Labels: enhancement

#43 Fixing backend issues
  client/src/App.js
  client/src/components/AboutUs.js
  client/src/components/Bicycle.js
  client/src/components/FeaturedShops.js
  client/src/components/Footer.js
  client/src/components/General.js
  client/src/components/HeroImage.js
  client/src/components/InfoCards.js
  client/src/components/Order.js
  client/src/components/Review.js
  client/src/components/SideBar.js
  client/src/components/UserInfo.js
  client/src/components/styles/profile.css
  client/src/pages/Home.js
  client/src/pages/Repairs.js
  client/src/pages/Signup.js
  client/src/pages/profile.js
  server/controllers/cyclist.js
  server/controllers/repair.js
  server/db/models/bikeshop.js
  server/db/models/user.js
  server/routes/secure/repair.js
Labels: enhancement

#65 Footer fix
  client/public/index.html
  client/src/components/Footer.js
  client/src/components/styles/homepage.css
  package.json
Labels: enhancement

#74 Adding reviews componenet
  client/package.json
  client/src/App.js
  client/src/components/Review.js
  client/src/components/styles/subpages.css
  client/src/pages/BikeShopPDP.js
  client/yarn.lock
  package.json
  server/controllers/user.js
  yarn.lock
Labels: enhancement

#97 created bicycle page
  client/src/components/Bicycle.js
  client/src/components/Bike.js
  client/src/pages/CreateCyclist.js
Labels: enhancement

#95 turned off caseignore and am now able to change casing of filenames
  server/controllers/serviceorder.js
Labels: enhancement

#96 DO NOT MERGE - Adding service orders
  client/src/components/Bicycle.js
  client/src/components/HeroImage.js
  client/src/components/RepairSelection.js
  client/src/context/AppContext.js
  client/src/pages/Appointment.js
  client/src/pages/BikeShopPDP.js
  client/src/pages/CreateBikeshop.js
  client/src/pages/CreateCyclist.js
  client/src/pages/Login.js
  client/src/pages/Repairs.js
  client/src/pages/Signup.js
  server/controllers/bicycle.js
  server/controllers/bikeshop.js
  server/controllers/cyclist.js
  server/controllers/repair.js
  server/controllers/serviceOrder.js
  server/controllers/serviceorder.js
  server/controllers/user.js
  server/db/models/bikeshop.js
  server/db/models/cyclist.js
  server/db/models/user.js
  server/middleware/authentication/index.js
  server/routes/secure/bicycle.js
  server/routes/secure/cyclist.js
  server/routes/secure/repair.js
  server/temp/mongoose.js
Labels: help wanted

#100 Creating readme jp
  README.md
Labels: documentation

#99 Creating community jp
  client/src/App.js
  client/src/components/styles/community.css
  client/src/pages/Community.js
Labels: enhancement

#89 Creating aboutus jp
  client/src/App.js
  client/src/components/AboutUs.js
  client/src/components/styles/aboutus.css
  client/src/pages/AboutUs.js
  client/src/pages/Home.js
  client/src/pages/Signup.js
Labels: enhancement

#101 Draft(Don't Merge) - Creating tracking jp
  client/src/App.js
  client/src/components/ProgressBar.js
  client/src/components/RepairControl.js
  client/src/components/styles/repairtracker.css
  client/src/pages/RepairTracker.js
  client/src/pages/Signup.js
Labels: help wanted

#112 chat component
  client/src/App.js
  client/src/components/Bicycle.js
  client/src/components/Chat.js
  client/src/components/RepairControl.js
  server/app.js
  server/controllers/message.js
  server/db/models/message.js
  server/routes/secure/message.js
Labels: enhancement
